name: tag

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          yarn install
          yarn test
          npm publish